import { useState, useCallback } from 'react';
import { env } from '@/config/env';

export const useMaplewatch = () => {
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  /**
   * Fetches the available providers and episodes from Maplewatch using AniList ID.
   * @param anilistId - The official AniList ID of the anime.
   * @returns The raw providers object or null if failed.
   */
  const fetchProviders = useCallback(async (anilistId: number | string) => {
    setLoading(true);
    setError(null);
    try {
      const response = await fetch(`${env.api.maplewatch}/episodes/${anilistId}`);
      if (!response.ok) throw new Error(`Maplewatch API Error: ${response.status}`);
      
      const data = await response.json();
      return data.providers || null;
    } catch (err: any) {
      console.error('[useMaplewatch] Failed to fetch providers:', err.message);
      setError(err.message);
      return null;
    } finally {
      setLoading(false);
    }
  }, []);

  /**
   * Fetches the streaming data (M3U8 links, subtitles) for a specific episode.
   * @param watchId - The unique watch ID generated by Maplewatch (e.g., watch/zoro/182255/sub/zoro-1)
   * @returns The raw stream object or null if failed.
   */
  const fetchStream = useCallback(async (watchId: string) => {
    setLoading(true);
    setError(null);
    try {
      const response = await fetch(`${env.api.maplewatch}/${watchId}`);
      if (!response.ok) throw new Error(`Maplewatch Stream Error: ${response.status}`);
      
      const data = await response.json();
      // Maplewatch returns a dynamic key (e.g., ssub, sdub), so we extract the first value
      const streamObj = Object.values(data)[0];
      return streamObj || null;
    } catch (err: any) {
      console.error('[useMaplewatch] Failed to fetch stream:', err.message);
      setError(err.message);
      return null;
    } finally {
      setLoading(false);
    }
  }, []);

  return {
    fetchProviders,
    fetchStream,
    loading,
    error
  };
};